# This is a basic workflow to help you get started with Actions
name: kapoor

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

jobs:
  build:
  
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      
      - name: Deploy app build to cise servers
        run: |
          rm -rf public_html/*
          cp -a -r public_html/
